name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '18'

      - name: Install Dependncies
        run:  sudo npm install
      
      - name: tshirts fail
        run: bash .github/workflows/expectfail.sh "node ./test/tshirts.test.js"

      - name: misaligned fail
        run: bash .github/workflows/expectfail.sh "node ./test/misaligned.test.js"

      - name: transmitter fail
        run: bash .github/workflows/expectfail.sh "node ./test/weatherreport.test.js"
